[package]
name = "rwge_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rwge = { path = "../Rust-WGPU-Game-Engine" }